// Questões novas, anexadas às 42 originais por build.mjs.
// Mesmo formato: t=tema exibido, s=slug do filtro, q=pergunta, o=alternativas,
// c=índice da correta, e=explicação.
export default [
  // B10 — Testes & qualidade
  { t: 'Testes', s: 'testes', q: 'Por que <code>getByRole</code> é preferido a <code>getByTestId</code> na Testing Library?', o: ['É mais rápido de executar', 'Testa o que o usuário e o leitor de tela realmente percebem, provando acessibilidade de quebra', 'testId não funciona em componentes de classe', 'getByRole não precisa de import extra'], c: 1, e: 'Testar por role/texto acessível prova, como efeito colateral, que o elemento é semântico e acessível — um <code>data-testid</code> passa mesmo numa <code>&lt;div&gt;</code> sem role nenhum. testId fica como último recurso, não primeira escolha.' },
  { t: 'Testes', s: 'testes', q: 'Qual a vantagem do MSW sobre mockar o módulo do cliente HTTP (ex.: <code>jest.mock(\'axios\')</code>)?', o: ['MSW é mais rápido em qualquer cenário', 'MSW intercepta na camada de rede, então o mesmo handler serve pro teste e pra rodar a aplicação sem backend', 'MSW elimina a necessidade de qualquer asserção', 'Mockar o módulo é sempre inválido'], c: 1, e: 'Mockar o módulo substitui a implementação e pula o código real de serialização/erro HTTP. MSW intercepta a requisição de verdade na rede — o app não sabe que está sendo testado, e o mock serve tanto em teste quanto em desenvolvimento local.' },
  { t: 'Testes', s: 'testes', q: 'Um teste E2E falha só às vezes no CI, nunca localmente. Qual é a causa mais provável antes de aumentar o timeout?', o: ['O CI tem uma versão diferente do Node', 'Dependência de ordem entre testes ou condição de corrida esperando por tempo fixo em vez de por condição', 'O Playwright não funciona em containers', 'Falta de cobertura de código'], c: 1, e: 'Aumentar timeout mascara, não resolve. As causas mais comuns são estado deixado por um teste anterior (ordem) ou o teste checar algo antes de ele estar pronto — a correção é esperar por condição, não por tempo fixo.' },
  { t: 'Testes', s: 'testes', q: 'Qual a diferença prática entre um <em>stub</em> e um <em>mock</em>?', o: ['São sinônimos exatos', 'Stub devolve resposta pronta pra alimentar o teste; mock também verifica se foi chamado como se esperava, virando parte da asserção', 'Mock é para banco de dados e stub para HTTP', 'Stub só existe em linguagens tipadas'], c: 1, e: 'Stub é entrada: substitui uma dependência pra o teste poder rodar. Mock é saída: além de substituir, ele registra as chamadas e o teste afirma sobre elas. Mock demais acopla o teste à implementação — a chamada muda, o teste quebra sem que nada tenha deixado de funcionar.' },
  { t: 'Testes', s: 'testes', q: 'Um componente tem um <code>setTimeout</code> de 5 segundos. Como testar o comportamento pós-timeout sem que a suíte demore 5 segundos?', o: ['Aumentar o timeout do test runner', 'Usar fake timers (vi.useFakeTimers / jest.useFakeTimers) e avançar o relógio manualmente', 'Reduzir o timeout no código de produção só para o teste', 'Não é possível testar código com timer'], c: 1, e: 'Fake timers substituem o relógio: o teste avança o tempo de forma determinística e instantânea. Além de rápido, elimina a instabilidade de teste que depende de tempo real — a causa número um de flakiness em teste de unidade.' },
  { t: 'Testes', s: 'testes', q: 'A cobertura de testes subiu de 60% para 95% e mesmo assim bugs continuam chegando em produção. O que isso indica?', o: ['A ferramenta de cobertura está com defeito', 'Cobertura mede linha executada, não asserção correta nem caso de borda coberto — é possível executar tudo sem verificar quase nada', 'É impossível: 95% de cobertura garante ausência de bugs', 'O problema é só falta de testes E2E'], c: 1, e: 'Cobertura é uma métrica de execução, não de verificação. Um teste que renderiza o componente inteiro e afirma apenas que ele não quebrou cobre muitas linhas e prova pouco. Serve pra achar o que nunca foi tocado; não serve como meta.' },

  // B11 — Acessibilidade
  { t: 'Acessibilidade', s: 'a11y', q: 'Um modal abre por cima da página. O que precisa acontecer com o foco do teclado?', o: ['Nada, o navegador cuida disso sozinho', 'Mover foco pra dentro do modal na abertura, prender o Tab nele, e devolver o foco ao elemento que abriu quando fechar', 'Remover o tabindex de toda a página', 'Só é necessário se o site usar leitor de tela'], c: 1, e: 'Sem gerenciar foco, quem navega por teclado continua no conteúdo coberto atrás do modal na abertura, e "perde" o foco ao fechar. É o padrão de dialog da WAI-ARIA APG.' },
  { t: 'Acessibilidade', s: 'a11y', q: 'Um toast de sucesso aparece e some em 3 segundos, sem nenhum atributo ARIA. Por que quem usa leitor de tela pode não perceber?', o: ['Leitores de tela não leem elementos com animação', 'Inserir conteúdo novo no DOM não é anunciado automaticamente — precisa de uma live region (ex.: role="status")', 'O CSS de opacidade bloqueia o leitor de tela', 'Toast nunca é acessível, mesmo com ARIA'], c: 1, e: 'Sem <code>aria-live</code> (direto ou via role="status"/"alert"), o leitor de tela não é avisado da mudança. role="status" tem aria-live="polite" implícito — o padrão certo pra notificação não crítica.' },
  { t: 'Acessibilidade', s: 'a11y', q: 'Qual nível de WCAG é o exigido pela maioria das leis de acessibilidade digital (ADA, EAA, LBI)?', o: ['A', 'AA', 'AAA', 'Não existe exigência legal, só recomendação'], c: 1, e: 'AA é o padrão de mercado e o citado na maioria da legislação. A própria W3C recomenda não exigir AAA no site inteiro, porque alguns critérios AAA são inviáveis pra certos tipos de conteúdo.' },
  { t: 'Acessibilidade', s: 'a11y', q: 'Por que <code>&lt;div onclick&gt;</code> com visual de botão é um problema de acessibilidade, mesmo com <code>role="button"</code> adicionado?', o: ['role="button" resolve completamente o problema', 'Ainda falta ser focável (tabindex) e responder a Enter e Espaço — o botão nativo traz os três comportamentos de graça', 'Divs nunca podem receber role', 'O problema é apenas visual, não funcional'], c: 1, e: 'Um <code>&lt;button&gt;</code> nativo é focável por teclado, aparece na ordem de tabulação, dispara com Enter e Espaço e é anunciado corretamente. Reproduzir isso numa div exige role + tabindex + handler de teclado — três chances de errar em vez de zero.' },
  { t: 'Acessibilidade', s: 'a11y', q: 'Qual é a primeira regra do ARIA, segundo a própria especificação?', o: ['Sempre adicionar aria-label em todo elemento interativo', 'Não usar ARIA: se existe um elemento HTML nativo com a semântica necessária, use ele', 'Usar role em todas as divs de layout', 'ARIA substitui HTML semântico em aplicações modernas'], c: 1, e: 'ARIA só descreve semântica, não adiciona comportamento nenhum. Elemento nativo traz semântica e comportamento juntos. ARIA mal aplicado é pior que ARIA nenhum, porque mente para a tecnologia assistiva com a confiança de um atributo explícito.' },
  { t: 'Acessibilidade', s: 'a11y', q: 'Qual é a razão mínima de contraste exigida pelo WCAG AA para texto normal?', o: ['3:1', '4.5:1', '7:1', '2:1'], c: 1, e: '4.5:1 para texto normal e 3:1 para texto grande (a partir de ~24px, ou 19px em negrito) e para componentes de interface. O nível AAA sobe para 7:1. É o critério mais fácil de verificar automaticamente e um dos mais violados.' },

  // B12 — CSS moderno
  { t: 'CSS', s: 'css', q: 'Duas regras CSS têm a mesma especificidade e miram o mesmo elemento, em camadas (@layer) diferentes. O que decide qual vence?', o: ['A especificidade decide, como sempre', 'A ordem de declaração das camadas — camada declarada depois sempre vence, independente de especificidade', 'A ordem alfabética do nome da camada', 'O navegador escolhe aleatoriamente'], c: 1, e: 'Entre camadas diferentes, a especificidade normal não decide — só a ordem de declaração das camadas. Dentro da mesma camada, a especificidade tradicional volta a valer.' },
  { t: 'CSS', s: 'css', q: 'Um componente precisa mudar de layout conforme o espaço do seu pai, não o tamanho da tela (o mesmo card aparece numa sidebar estreita e num conteúdo largo). Qual ferramenta resolve?', o: ['Media query', 'Container query', 'Flexbox sozinho resolve', '@supports'], c: 1, e: 'Media query olha o viewport, não o espaço real do componente. Container query (container-type + @container) estiliza baseado no espaço disponível do elemento pai, tornando o componente reutilizável em qualquer contexto de layout.' },
  { t: 'CSS', s: 'css', q: 'Animar <code>transform: translateX()</code> é mais suave que animar <code>left</code>. Por quê?', o: ['transform usa menos memória', 'left dispara recálculo de layout a cada frame; transform só afeta a fase de composite, muitas vezes na GPU', 'left não é suportado em navegadores modernos', 'Não há diferença real de performance'], c: 1, e: 'left muda a posição no fluxo do documento (dispara layout + paint a cada frame). transform não afeta layout — o navegador só move a camada já pintada na composição, tipicamente acelerada por GPU.' },
  { t: 'CSS', s: 'css', q: 'Um <code>z-index: 9999</code> não coloca o elemento na frente de outro com <code>z-index: 1</code>. Qual é a explicação mais provável?', o: ['9999 é um valor alto demais e o navegador ignora', 'Os dois estão em contextos de empilhamento diferentes — o z-index só compete dentro do mesmo contexto', 'z-index só funciona com position: absolute', 'É um bug conhecido dos navegadores'], c: 1, e: 'Um ancestral com opacity menor que 1, transform, filter, will-change ou position fixed cria um contexto de empilhamento novo. Dentro dele, o filho fica preso: por maior que seja o z-index, ele só disputa com irmãos daquele contexto.' },
  { t: 'CSS', s: 'css', q: 'Qual a diferença entre <code>gap</code> e <code>margin</code> para espaçar itens de um grid ou flex?', o: ['São equivalentes em qualquer caso', 'gap só cria espaço entre os itens, sem espaço na borda externa nem colapso de margem — margin exige compensar o último item', 'margin não funciona dentro de flex containers', 'gap só funciona em grid, não em flex'], c: 1, e: 'Com margin, o último item deixa um espaço sobrando na borda e é preciso corrigir com :last-child ou margem negativa no container. gap é aplicado pelo container só entre os itens, o que elimina o caso especial.' },
  { t: 'CSS', s: 'css', q: 'Por que <code>:where(.btn)</code> é útil ao escrever uma biblioteca de componentes?', o: ['É mais rápido de processar que .btn', ':where() tem especificidade zero, então quem consome consegue sobrescrever com um seletor simples', ':where() funciona em navegadores antigos', 'É sinônimo de :is() em todos os aspectos'], c: 1, e: ':is() assume a especificidade do seletor mais específico dentro dele; :where() zera. Estilo base declarado com :where() é sobrescrevível por uma única classe do consumidor, sem guerra de especificidade nem !important.' },

  // B13 — Navegador & performance
  { t: 'Performance', s: 'performance-fe', q: 'Por que um <code>&lt;script&gt;</code> no &lt;head&gt; sem defer nem async atrasa a primeira pintura da página?', o: ['Scripts sempre bloqueiam CSS', 'O parser do HTML para de construir o DOM, baixa e executa o script antes de continuar', 'O navegador prioriza JavaScript sobre HTML por padrão', 'Isso só acontece em conexões lentas'], c: 1, e: 'O parser pode encontrar document.write no script, então ele para e executa antes de seguir. defer baixa em paralelo e roda só depois do HTML parseado; async roda assim que pronto, fora de ordem.' },
  { t: 'Performance', s: 'performance-fe', q: 'Uma rota carrega um editor de texto rico de 300kb usado por 5% dos usuários. Qual técnica evita que os outros 95% paguem esse custo?', o: ['Minificação agressiva', 'Code splitting: import() dinâmico carregando o editor só quando ele aparece na tela', 'Server-side rendering', 'Aumentar o cache do CDN'], c: 1, e: 'Split por componente com import() dinâmico (ou React.lazy) adia o download até o componente realmente ser necessário — os 95% que nunca abrem o editor nunca baixam esse bundle.' },
  { t: 'Performance', s: 'performance-fe', q: 'O texto pisca de uma fonte genérica pra uma fonte customizada (FOUT) e causa um "pulo" de layout perceptível. O que reduz o pulo, além de pré-carregar a fonte?', o: ['font-display: swap sozinho já resolve o pulo', 'Escolher uma fonte de fallback com métricas parecidas (ou usar size-adjust) pra minimizar a diferença de largura', 'Remover a fonte customizada', 'Usar apenas fontes do sistema operacional'], c: 1, e: 'font-display: swap evita texto invisível (FOIT) mas não evita o pulo em si — troca um problema pelo outro. Aproximar as métricas da fonte de fallback da fonte final é o que reduz o deslocamento de layout quando a troca acontece.' },
  { t: 'Performance', s: 'performance-fe', q: 'O que a métrica INP (Interaction to Next Paint) mede, e por que ela substituiu o FID?', o: ['O tempo de carregamento inicial da página', 'A latência das interações ao longo de toda a visita, até a próxima pintura — enquanto o FID media só o atraso da primeira interação', 'O tempo de resposta do servidor', 'A quantidade de JavaScript baixado'], c: 1, e: 'FID media apenas o atraso inicial até o handler começar, ignorando o custo do processamento e da renderização. INP considera a interação inteira, e todas elas, refletindo bem melhor a sensação de travamento percebida pelo usuário.' },
  { t: 'Performance', s: 'performance-fe', q: 'Uma imagem grande no topo da página aparece só depois de um tempo e empurra o conteúdo. Além de otimizar o arquivo, o que evita o deslocamento de layout?', o: ['Usar loading="lazy" na imagem', 'Reservar o espaço declarando width e height (ou aspect-ratio) para o navegador saber o tamanho antes de baixar', 'Carregar a imagem via JavaScript', 'Reduzir a qualidade da compressão'], c: 1, e: 'Sem dimensão declarada, o navegador só descobre o tamanho quando a imagem chega, e reflui tudo abaixo — é a principal causa de CLS. Vale o contrário para loading="lazy" em imagem do topo: ela atrasa justamente o que deveria ser prioritário.' },
  { t: 'Performance', s: 'performance-fe', q: 'Uma tarefa de JavaScript de 300ms trava a página. Por que dividi-la em pedaços menores melhora a resposta ao clique?', o: ['O total de processamento fica menor', 'A thread principal é única: tarefa longa impede o navegador de processar eventos e pintar até terminar — ceder o controle entre os pedaços abre janelas para isso', 'O navegador passa a usar mais núcleos automaticamente', 'Só melhora a percepção, sem efeito técnico real'], c: 1, e: 'Uma long task bloqueia entrada e pintura durante toda a sua execução. Quebrar em pedaços com yield (scheduler.yield, setTimeout, ou processamento em lotes) deixa o navegador atender o clique entre eles. Para trabalho realmente pesado, Web Worker tira da thread principal.' },

  // B14 — Front-end system design
  { t: 'FE System Design', s: 'fe-sysdesign', q: 'Num autocomplete, a resposta da busca por "a" chega depois da resposta por "abc" (a requisição mais lenta demorou mais). Sem tratamento, o que aparece na tela?', o: ['A lista de "abc" fica congelada', 'A lista de "a" sobrescreve a de "abc" por ter chegado por último', 'O navegador bloqueia a segunda requisição automaticamente', 'Nenhuma sugestão aparece'], c: 1, e: 'É uma condição de corrida de rede clássica. Corrige-se com AbortController cancelando a requisição anterior a cada nova tecla, ou um número de sequência que ignora resposta desatualizada.' },
  { t: 'FE System Design', s: 'fe-sysdesign', q: 'Por que um feed que recebe posts novos em tempo real deveria usar paginação por cursor em vez de offset?', o: ['Cursor é mais fácil de implementar', 'Offset quebra quando um item é inserido antes da posição atual enquanto o usuário rola, duplicando ou pulando itens', 'Offset não existe em bancos NoSQL', 'Cursor não precisa de índice no banco'], c: 1, e: 'Offset pede "a página N" por posição numérica; inserção concorrente desloca todo mundo. Cursor pede "os itens depois deste id/timestamp real", que permanece estável mesmo com inserção simultânea.' },
  { t: 'FE System Design', s: 'fe-sysdesign', q: 'Uma atualização otimista de "curtir" é aplicada na UI antes da resposta do servidor. O servidor rejeita. Qual é a forma correta de desfazer?', o: ['Recarregar a página inteira', 'Reverter para o estado anterior salvo (snapshot) e mostrar uma mensagem explicando o que houve', 'Ignorar o erro, já que o usuário não vai perceber', 'Tentar de novo automaticamente até funcionar'], c: 1, e: 'É necessário guardar o estado anterior antes de aplicar a mudança otimista, reverter para ele no erro (rollback), e comunicar — nunca reverter em silêncio, porque o usuário viu a mudança acontecer.' },
  { t: 'FE System Design', s: 'fe-sysdesign', q: 'O que significa cada letra do framework RADIO, usado em entrevista de front-end system design?', o: ['Render, API, Data, Interface, Optimization', 'Requirements, Architecture, Data model, Interface (API), Optimization', 'React, Angular, Django, IO, Ops', 'Requests, Async, Database, Interaction, Output'], c: 1, e: 'Requirements (esclarecer escopo e restrições), Architecture (componentes e responsabilidades), Data model (estado do cliente e do servidor), Interface (contrato de API entre as peças) e Optimization (performance, acessibilidade, rede). Seguir a ordem evita o erro mais comum: pular direto pro desenho.' },
  { t: 'FE System Design', s: 'fe-sysdesign', q: 'Uma tabela precisa exibir 50 mil linhas. Por que a virtualização resolve, e qual é o custo que ela traz?', o: ['Não há custo, é sempre a melhor solução', 'Renderiza só as linhas visíveis (mais uma folga), reduzindo o número de nós no DOM — ao custo de quebrar Ctrl+F, seleção de tudo e exigir altura conhecida ou medida', 'Ela comprime os dados no servidor', 'Ela só funciona com paginação por cursor'], c: 1, e: 'O gargalo é o número de nós no DOM, não o volume de dados em memória. Virtualizar corta isso drasticamente, mas o conteúdo fora da janela deixa de existir na página: busca do navegador, impressão e leitor de tela precisam de tratamento à parte.' },
  { t: 'FE System Design', s: 'fe-sysdesign', q: 'Num editor colaborativo simples, qual é a diferença entre WebSocket e SSE (Server-Sent Events)?', o: ['SSE é mais rápido em qualquer cenário', 'WebSocket é bidirecional sobre uma conexão própria; SSE é unidirecional (servidor → cliente) sobre HTTP, com reconexão automática embutida', 'WebSocket não funciona atrás de proxy', 'SSE permite enviar dados binários e WebSocket não'], c: 1, e: 'Se o cliente também escreve com frequência, WebSocket. Se ele só recebe atualizações (notificação, cotação, progresso de job), SSE é mais simples: é HTTP comum, atravessa proxy sem drama e reconecta sozinho com Last-Event-ID.' },

  // B15 — React avançado
  { t: 'React', s: 'react-avancado', q: 'Com o React Compiler ativo, você ainda pode precisar escrever useMemo manualmente. Quando?', o: ['Nunca mais é necessário sob nenhuma circunstância', 'Quando o código quebra as Regras do React (mutação fora de render, efeito colateral no corpo do componente) e o compiler não pode memoizar com segurança', 'Sempre que o componente tem mais de 3 props', 'Apenas em Server Components'], c: 1, e: 'O compiler memoiza automaticamente código que segue as Regras do React. Código que as quebra pode não ser otimizável com segurança — o compiler prefere não memoizar a memoizar errado, e useMemo manual ainda cobre esses casos e cálculos fora de componentes.' },
  { t: 'React', s: 'react-avancado', q: 'Uma lib como TanStack Query resolve o quê que um useEffect + fetch manual não resolve sozinho, pra dado que vem de uma API?', o: ['Apenas estiliza o estado de loading', 'Noção de staleness com refetch automático (foco, reconexão) e deduplicação de requisições simultâneas pelo mesmo dado', 'Substitui a necessidade de um backend', 'Faz cache permanente que nunca expira'], c: 1, e: 'A lib trata o dado como "estado de servidor": sabe quando ficou desatualizado e refaz a busca automaticamente em certos eventos, além de deduplicar pedidos concorrentes pelo mesmo recurso — tudo isso replicável à mão, mas com bem mais código.' },
  { t: 'React', s: 'react-avancado', q: 'Um componente tem 15 props booleanas controlando o que é renderizado. Qual é o padrão que resolve isso trocando configuração por composição?', o: ['Prop drilling', 'Compound components (ex.: <Card><Card.Icon/><Card.Footer/></Card>)', 'HOC (higher-order component)', 'Context API sozinho'], c: 1, e: 'Compound components deixa quem usa decidir o que existe simplesmente incluindo ou não a subpeça, sem prop booleana nenhuma — evita a combinatória de condicionais dentro de um único componente configurável.' },
  { t: 'React', s: 'react-avancado', q: 'Um <code>useEffect</code> busca dados e atualiza o estado, mas o componente desmonta antes da resposta chegar. Qual é o tratamento correto?', o: ['Ignorar, o React lida com isso sozinho', 'Cancelar com AbortController (ou marcar como ignorado) na função de limpeza do efeito', 'Envolver o setState num try/catch', 'Usar useLayoutEffect no lugar'], c: 1, e: 'Sem cancelar, a resposta tardia pode sobrescrever estado de uma requisição mais nova (condição de corrida) e mantém trabalho vivo sem necessidade. A função de retorno do efeito existe exatamente pra isso — e o mesmo cleanup resolve o caso de o efeito rodar duas vezes no StrictMode.' },
  { t: 'React', s: 'react-avancado', q: 'Colocar todo o estado da aplicação num único Context causa qual problema de performance?', o: ['O Context deixa de funcionar acima de certo tamanho', 'Qualquer mudança no valor do provider re-renderiza todos os consumidores, mesmo os que usam só uma parte do estado', 'Context não funciona com Server Components', 'O estado é perdido a cada render'], c: 1, e: 'Context não tem seletor: quem consome, consome o valor inteiro. As saídas são dividir em vários contexts por frequência de mudança, memoizar o value, ou usar uma store externa (Zustand, Redux) que permita assinar só um pedaço.' },
  { t: 'React', s: 'react-avancado', q: 'Qual a diferença entre um Server Component e um Client Component marcado com <code>"use client"</code>?', o: ['Server Component roda mais rápido no navegador', 'Server Component executa só no servidor, não vai no bundle e não pode ter estado nem evento; Client Component é enviado ao navegador e hidrata', 'São a mesma coisa com nomes diferentes', 'Client Component não pode fazer fetch de dados'], c: 1, e: 'Server Component pode acessar banco e segredo diretamente e custa zero JavaScript no cliente, em troca de não ter useState, useEffect nem handler de evento. O padrão é manter o Server Component como raiz e descer para "use client" só nas folhas interativas.' },

  // B16 — Design de APIs
  { t: 'APIs', s: 'apis', q: 'Um app mobile precisa de dado de 4 endpoints REST diferentes pra montar uma tela, cada requisição com 200ms de latência de rede. Qual padrão reduz isso a uma chamada do cliente?', o: ['GraphQL é a única solução possível', 'BFF: uma camada fina específica pro cliente que agrega as 4 chamadas no servidor e devolve um payload único', 'Aumentar o timeout do cliente', 'Usar WebSocket em vez de REST'], c: 1, e: 'Um Backend for Frontend concentra as chamadas onde a latência entre elas é baixa (dentro da infraestrutura do servidor) e devolve tudo agregado — o cliente paga a latência de rede uma vez, não quatro.' },
  { t: 'APIs', s: 'apis', q: 'Por que resolvers do GraphQL sofrem com o problema N+1, e qual a correção padrão?', o: ['GraphQL não tem esse problema, só REST', 'Cada campo de relação numa lista dispara uma query por item por padrão; DataLoader agrupa (batch) essas chamadas feitas no mesmo tick numa consulta só', 'A correção é sempre usar REST em vez de GraphQL', 'O problema só existe em bancos NoSQL'], c: 1, e: 'Uma lista de N posts com autor dispara 1 query pros posts + N queries pros autores por padrão. DataLoader junta as N chamadas de autor feitas no mesmo tick numa única consulta em lote (WHERE id IN (...)).' },
  { t: 'APIs', s: 'apis', q: 'Um provedor de pagamento reenvia o mesmo webhook duas vezes (entrega at-least-once). O que garante que seu handler não duplica o efeito?', o: ['Confiar que o provedor não reenvia sem motivo', 'Gravar o id do evento com constraint UNIQUE na mesma transação do efeito, fazendo a segunda execução virar no-op', 'Aumentar o timeout de resposta do webhook', 'Ignorar eventos repetidos pelo timestamp'], c: 1, e: 'Idempotência do lado de quem recebe é a defesa real: uma constraint UNIQUE na mesma transação garante que a segunda tentativa esbarra e não duplica o efeito, independente de quantas vezes o evento chegue.' },
  { t: 'APIs', s: 'apis', q: 'Em que caso a paginação por cursor é claramente preferível à paginação por offset?', o: ['Quando é preciso pular direto para a página 47', 'Em lista grande que recebe inserções enquanto é percorrida — offset duplica ou pula itens, e ainda fica lento por precisar contar as linhas anteriores', 'Cursor é sempre preferível, sem exceção', 'Quando o banco é NoSQL'], c: 1, e: 'OFFSET 100000 obriga o banco a varrer e descartar cem mil linhas, e qualquer inserção desloca todo mundo. Cursor ancora numa chave ordenada e estável (WHERE id < ultimo), com custo constante. O que se perde é justamente pular para uma página arbitrária.' },
  { t: 'APIs', s: 'apis', q: 'Qual é a forma mais segura de versionar uma API pública que precisa mudar o formato de um campo?', o: ['Mudar direto: quem consome se adapta', 'Adicionar o campo novo em paralelo, marcar o antigo como obsoleto com prazo e só então remover — mudança aditiva antes de quebrar contrato', 'Criar uma API totalmente nova a cada mudança', 'Usar sempre v2, v3, v4 no caminho para qualquer alteração'], c: 1, e: 'Mudança aditiva não quebra cliente nenhum: os antigos ignoram o campo novo. Versão no caminho (/v2) é o último recurso, porque obriga a manter duas implementações. O ciclo é adicionar, avisar, medir o uso do antigo, e remover só quando chegar a zero.' },
  { t: 'APIs', s: 'apis', q: 'Por que enviar um erro de validação como <code>200 OK</code> com <code>{ "erro": "..." }</code> no corpo é considerado má prática?', o: ['Consome mais banda', 'Quebra o contrato do HTTP: cache, proxy, cliente HTTP, retry automático e monitoramento tratam 2xx como sucesso, e o erro fica invisível', 'O navegador bloqueia respostas assim', 'Não há problema algum nessa abordagem'], c: 1, e: 'O status é a parte da resposta que a infraestrutura inteira entende sem ler o corpo. Erro em 200 não aparece na taxa de erro do monitoramento, pode ser cacheado e engana qualquer política de retry. Validação inválida é 400 ou 422, com detalhe por campo no corpo.' },

  // B17 — Produção
  { t: 'Produção', s: 'producao', q: 'Por que "alertar quando a CPU passa de 80%" costuma gerar mais ruído do que "alertar quando a latência p99 passa de 2s"?', o: ['CPU é mais difícil de medir', 'CPU alta é uma causa possível, não necessariamente um sintoma que o usuário sente; latência é o que o usuário experimenta de fato', 'Latência não pode ser medida com precisão', 'Não há diferença real entre os dois'], c: 1, e: 'A prática recomendada é alertar no sintoma percebido pelo usuário (latência, taxa de erro) e usar métricas de causa (CPU, memória) só para investigar depois que o alerta de sintoma já disparou.' },
  { t: 'Produção', s: 'producao', q: 'Sua SLO mensal de disponibilidade já consumiu metade do error budget, faltando duas semanas do mês. O que a prática de SRE recomenda?', o: ['Ignorar, já que ainda resta metade do budget', 'Desacelerar lançamentos arriscados e priorizar confiabilidade até o budget renovar', 'Aumentar a SLO imediatamente pra evitar o problema', 'Parar todo deploy até o fim do mês'], c: 1, e: 'O error budget existe pra negociar entre velocidade de lançamento e confiabilidade. Consumido em excesso, a prática comum é reduzir risco (menos lançamentos arriscados) pelo resto do período, sem necessariamente parar tudo.' },
  { t: 'Produção', s: 'producao', q: 'O que muda, na prática, num postmortem "sem culpa" (blameless) em relação a um postmortem comum?', o: ['Não se investiga a causa raiz', 'O foco vai para o sistema que permitiu o erro acontecer, não para punir quem cometeu o erro — o que gera relatos mais completos e honestos', 'Ninguém é informado do incidente', 'É apenas um nome mais educado pro mesmo processo'], c: 1, e: 'Assumir que a pessoa tomou a melhor decisão possível com a informação disponível desloca o foco pro sistema (falta de alerta, processo, documentação) — e isso remove o incentivo de esconder o próprio erro, gerando relatos mais completos.' },
  { t: 'Produção', s: 'producao', q: 'Qual é a diferença entre os "três pilares" — logs, métricas e traces — em termos do que cada um responde?', o: ['São três nomes para a mesma coleta de dados', 'Métrica responde "há um problema e qual a magnitude"; trace responde "onde, no caminho da requisição"; log responde "o que exatamente aconteceu naquele ponto"', 'Log substitui os outros dois em sistemas pequenos', 'Trace só serve para bancos de dados'], c: 1, e: 'A investigação normalmente percorre os três nessa ordem: o alerta vem da métrica agregada, o trace mostra qual serviço ou consulta consumiu o tempo, e o log daquele span traz o detalhe. Cada um é caro e barato em dimensões diferentes.' },
  { t: 'Produção', s: 'producao', q: 'Por que uma feature flag esquecida no código depois do lançamento é considerada dívida técnica?', o: ['Consome muita memória em produção', 'Cada flag viva dobra os caminhos possíveis de execução, e a combinação delas produz estados que ninguém testa', 'Flags deixam o deploy mais lento', 'Não é dívida: manter a flag é sempre mais seguro'], c: 1, e: 'Dez flags esquecidas são 1024 combinações teóricas de comportamento. A prática recomendada é tratar flag de lançamento como temporária, com dono e prazo, e remover assim que o lançamento se consolidar — flags de operação (kill switch) são a exceção legítima e permanente.' },
  { t: 'Produção', s: 'producao', q: 'Qual a diferença entre um deploy blue-green e um canary release?', o: ['São nomes diferentes para a mesma estratégia', 'Blue-green troca 100% do tráfego de um ambiente para o outro de uma vez (rollback instantâneo); canary envia uma fração pequena para a versão nova e aumenta gradualmente', 'Canary exige parar a aplicação; blue-green não', 'Blue-green só funciona em Kubernetes'], c: 1, e: 'Blue-green otimiza a velocidade do rollback, mantendo dois ambientes completos. Canary otimiza o tamanho do estrago: se algo quebrar, atingiu 1% dos usuários, e as métricas do grupo canário decidem se a implantação continua.' },

  // B18 — Senioridade
  { t: 'Senioridade', s: 'senioridade', q: 'Qual é a diferença central entre o esperado de um engenheiro pleno e de um sênior, além de conhecimento técnico?', o: ['Sênior escreve código mais rápido', 'Escopo de decisão e capacidade de operar bem com ambiguidade, comunicando trade-offs por escrito', 'Sênior não precisa mais revisar código de outros', 'A diferença é só o tempo de empresa'], c: 1, e: 'Pleno executa bem um problema já definido; sênior é chamado justamente quando o problema não está bem definido, precisando decidir o que construir e comunicar o porquê — não apenas saber mais sintaxe ou API.' },
  { t: 'Senioridade', s: 'senioridade', q: 'Num code review, qual a diferença prática entre marcar um comentário como bloqueante e como sugestão?', o: ['Não há diferença, todo comentário deve ser tratado igual', 'Bloqueante exige mudança antes do merge (bug, falha de segurança); sugestão é uma opinião válida sem travar o merge', 'Sugestão é sempre ignorada pelo autor', 'Bloqueante só pode vir do tech lead'], c: 1, e: 'Sem essa distinção explícita, todo comentário vira implicitamente bloqueante e o review fica lento e desgastante — distinguir os dois deixa claro o que realmente precisa mudar versus o que é só uma consideração.' },
  { t: 'Senioridade', s: 'senioridade', q: 'Você discordou tecnicamente de uma decisão do tech lead, argumentou, e ele decidiu seguir do jeito dele. O que "discordar e se comprometer" significa na prática?', o: ['Continuar insistindo na reunião seguinte', 'Registrar a discordância uma vez, e então executar a decisão com o mesmo empenho de quem concorda, sem sabotar passivamente', 'Sabotar silenciosamente a implementação', 'Escalar imediatamente para um nível acima'], c: 1, e: 'É registrar objeção de forma clara, garantir que a decisão considerou os fatos, e então executar com empenho real — reservado para decisões em que você genuinamente discorda, não para todo desacordo de preferência.' },
  { t: 'Senioridade', s: 'senioridade', q: 'Qual é a função principal de um design doc antes de um projeto grande começar?', o: ['Documentar o sistema depois de pronto', 'Tornar a decisão revisável enquanto ela ainda é barata de mudar, e alinhar as pessoas afetadas antes do código existir', 'Cumprir uma exigência formal do processo', 'Substituir a necessidade de code review'], c: 1, e: 'O valor está em receber objeção quando mudar de ideia custa uma reunião, e não três semanas de implementação. A seção mais importante costuma ser a de alternativas consideradas e por que foram descartadas — é ela que mostra que houve comparação.' },
  { t: 'Senioridade', s: 'senioridade', q: 'Numa resposta STAR, qual é o erro mais comum de quem se prepara pouco?', o: ['Usar exemplos de projetos pessoais', 'Gastar a maior parte do tempo na Situação e responder em "nós", deixando a Ação individual e o Resultado numérico de fora', 'Mencionar tecnologias específicas', 'Escolher uma história que não deu certo'], c: 1, e: 'O entrevistador precisa saber o que você fez e o que mudou por causa disso. Contexto longo demais e narrativa em primeira pessoa do plural escondem exatamente as duas informações avaliadas — e Resultado sem número vira impressão, não evidência.' },
  { t: 'Senioridade', s: 'senioridade', q: 'Segundo as práticas de code review do Google, qual é o padrão para aprovar um pull request?', o: ['O código precisa estar perfeito', 'Ele deve melhorar a saúde geral do código, mesmo que não esteja perfeito — travar por perfeição é pior que aprovar uma melhoria', 'Deve seguir exatamente o estilo que o revisor usaria', 'Precisa de aprovação de pelo menos três pessoas'], c: 1, e: 'O padrão explícito é "melhora a saúde do código?". Perfeição como critério paralisa o time e desincentiva melhorias incrementais. Preferência pessoal de estilo não é motivo para bloquear — é sugestão, e a distinção deve ficar explícita no comentário.' },

  // B19 — Processo seletivo
  { t: 'Processo seletivo', s: 'processo', q: 'Um recrutador pergunta sua pretensão salarial antes de revelar a faixa da vaga. Qual é a resposta mais defensável?', o: ['Dar um número alto de propósito', 'Devolver a pergunta pedindo a faixa orçada da posição antes de dar um número', 'Recusar responder e encerrar a conversa', 'Dar o número mais baixo que aceitaria'], c: 1, e: 'Quem fala um número primeiro perde alavancagem de negociação — se for baixo, ancora abaixo do que a empresa pagaria; se for alto sem saber a faixa, pode ser descartado sem conversa. Pedir a faixa primeiro é a prática recomendada.' },
  { t: 'Processo seletivo', s: 'processo', q: 'Por que "responsável por desenvolvimento de features" é uma linha mais fraca de currículo que "reduzi o tempo de build de 8min pra 2min removendo dependência circular"?', o: ['A primeira é mais curta e objetiva', 'A primeira descreve responsabilidade genérica; a segunda tem causa, ação e resultado quantificado', 'Não há diferença real de qualidade', 'A segunda menciona tecnologia específica, o que é sempre pior'], c: 1, e: 'A frase genérica poderia ter sido escrita por qualquer pessoa no cargo. A segunda prova impacto mensurável e específico, que é o que recrutador técnico procura ao filtrar currículos.' },
  { t: 'Processo seletivo', s: 'processo', q: 'Comparado a um processo típico no Brasil, qual o peso da entrevista comportamental num loop de big tech no exterior?', o: ['É sempre menos importante que a técnica', 'Costuma ser uma rodada inteira separada, com peso equivalente a uma rodada técnica e influência direta no nível oferecido', 'Não existe entrevista comportamental fora do Brasil', 'É substituída por um teste de personalidade automatizado'], c: 1, e: 'No exterior, comportamental frequentemente é rodada própria que ajuda a decidir nível (sênior vs. staff, por exemplo) — não é um "extra" superficial como costuma ser tratado em processos mais curtos no Brasil.' },
  { t: 'Processo seletivo', s: 'processo', q: 'Qual a diferença prática, para quem mora no Brasil, entre ser contratado como <em>contractor</em> (PJ) e via <em>Employer of Record</em> (EOR) por uma empresa estrangeira?', o: ['Nenhuma, são termos equivalentes', 'Como contractor você emite nota e assume impostos e benefícios; via EOR uma empresa local te contrata formalmente pela estrangeira, com vínculo e benefícios locais', 'EOR significa trabalhar sem contrato', 'Contractor só é permitido para pessoa física'], c: 1, e: 'É a diferença entre receber bruto e organizar tudo sozinho (contabilidade, férias, previdência, câmbio) e ter uma entidade local intermediando com vínculo formal. Muda o líquido, a estabilidade e a comparação de propostas — e por isso a pergunta deve ser feita cedo no processo.' },
  { t: 'Processo seletivo', s: 'processo', q: 'Numa entrevista técnica em inglês, você não entendeu completamente o enunciado. Qual é a melhor conduta?', o: ['Começar a codificar e torcer para acertar o que foi pedido', 'Reformular o enunciado com as suas palavras e pedir confirmação antes de começar', 'Pedir para mudar a entrevista para português', 'Pedir mais tempo sem explicar o motivo'], c: 1, e: 'Reformular ("só pra confirmar: a entrada é um array ordenado e eu devolvo os índices, certo?") é conduta esperada de um sênior mesmo em português — e resolve o problema de idioma sem parecer fraqueza. Resolver o problema errado é a pior saída possível.' },
  { t: 'Processo seletivo', s: 'processo', q: 'Você recebeu uma oferta com prazo curto para responder e ainda tem outro processo em andamento. Qual é a conduta mais defensável?', o: ['Aceitar imediatamente para não perder a vaga', 'Agradecer, demonstrar interesse real e pedir um prazo específico, avisando o outro processo de que existe uma oferta com data', 'Aceitar e continuar entrevistando para desistir depois', 'Ignorar o prazo e responder quando puder'], c: 1, e: 'Pedir prazo com uma data concreta é normal e quase sempre aceito. E avisar o outro processo de que existe oferta com prazo costuma acelerá-lo — é informação legítima, não pressão. Aceitar para depois desistir queima a ponte com quem mais provavelmente vai te reencontrar no mercado.' },
];
