// Questões novas, anexadas às 42 originais por build.mjs.
// Mesmo formato: t=tema exibido, s=slug do filtro, q=pergunta, o=alternativas,
// c=índice da correta, e=explicação.
export default [
  // B10 — Testes & qualidade
  { t: 'Testes', s: 'testes', q: 'Por que <code>getByRole</code> é preferido a <code>getByTestId</code> na Testing Library?', o: ['É mais rápido de executar', 'Testa o que o usuário e o leitor de tela realmente percebem, provando acessibilidade de quebra', 'testId não funciona em componentes de classe', 'getByRole não precisa de import extra'], c: 1, e: 'Testar por role/texto acessível prova, como efeito colateral, que o elemento é semântico e acessível — um <code>data-testid</code> passa mesmo numa <code>&lt;div&gt;</code> sem role nenhum. testId fica como último recurso, não primeira escolha.' },
  { t: 'Testes', s: 'testes', q: 'Qual a vantagem do MSW sobre mockar o módulo do cliente HTTP (ex.: <code>jest.mock(\'axios\')</code>)?', o: ['MSW é mais rápido em qualquer cenário', 'MSW intercepta na camada de rede, então o mesmo handler serve pro teste e pra rodar a aplicação sem backend', 'MSW elimina a necessidade de qualquer asserção', 'Mockar o módulo é sempre inválido'], c: 1, e: 'Mockar o módulo substitui a implementação e pula o código real de serialização/erro HTTP. MSW intercepta a requisição de verdade na rede — o app não sabe que está sendo testado, e o mock serve tanto em teste quanto em desenvolvimento local.' },
  { t: 'Testes', s: 'testes', q: 'Um teste E2E falha só às vezes no CI, nunca localmente. Qual é a causa mais provável antes de aumentar o timeout?', o: ['O CI tem uma versão diferente do Node', 'Dependência de ordem entre testes ou condição de corrida esperando por tempo fixo em vez de por condição', 'O Playwright não funciona em containers', 'Falta de cobertura de código'], c: 1, e: 'Aumentar timeout mascara, não resolve. As causas mais comuns são estado deixado por um teste anterior (ordem) ou o teste checar algo antes de ele estar pronto — a correção é esperar por condição, não por tempo fixo.' },

  // B11 — Acessibilidade
  { t: 'Acessibilidade', s: 'a11y', q: 'Um modal abre por cima da página. O que precisa acontecer com o foco do teclado?', o: ['Nada, o navegador cuida disso sozinho', 'Mover foco pra dentro do modal na abertura, prender o Tab nele, e devolver o foco ao elemento que abriu quando fechar', 'Remover o tabindex de toda a página', 'Só é necessário se o site usar leitor de tela'], c: 1, e: 'Sem gerenciar foco, quem navega por teclado continua no conteúdo coberto atrás do modal na abertura, e "perde" o foco ao fechar. É o padrão de dialog da WAI-ARIA APG.' },
  { t: 'Acessibilidade', s: 'a11y', q: 'Um toast de sucesso aparece e some em 3 segundos, sem nenhum atributo ARIA. Por que quem usa leitor de tela pode não perceber?', o: ['Leitores de tela não leem elementos com animação', 'Inserir conteúdo novo no DOM não é anunciado automaticamente — precisa de uma live region (ex.: role="status")', 'O CSS de opacidade bloqueia o leitor de tela', 'Toast nunca é acessível, mesmo com ARIA'], c: 1, e: 'Sem <code>aria-live</code> (direto ou via role="status"/"alert"), o leitor de tela não é avisado da mudança. role="status" tem aria-live="polite" implícito — o padrão certo pra notificação não crítica.' },
  { t: 'Acessibilidade', s: 'a11y', q: 'Qual nível de WCAG é o exigido pela maioria das leis de acessibilidade digital (ADA, EAA, LBI)?', o: ['A', 'AA', 'AAA', 'Não existe exigência legal, só recomendação'], c: 1, e: 'AA é o padrão de mercado e o citado na maioria da legislação. A própria W3C recomenda não exigir AAA no site inteiro, porque alguns critérios AAA são inviáveis pra certos tipos de conteúdo.' },

  // B12 — CSS moderno
  { t: 'CSS', s: 'css', q: 'Duas regras CSS têm a mesma especificidade e miram o mesmo elemento, em camadas (@layer) diferentes. O que decide qual vence?', o: ['A especificidade decide, como sempre', 'A ordem de declaração das camadas — camada declarada depois sempre vence, independente de especificidade', 'A ordem alfabética do nome da camada', 'O navegador escolhe aleatoriamente'], c: 1, e: 'Entre camadas diferentes, a especificidade normal não decide — só a ordem de declaração das camadas. Dentro da mesma camada, a especificidade tradicional volta a valer.' },
  { t: 'CSS', s: 'css', q: 'Um componente precisa mudar de layout conforme o espaço do seu pai, não o tamanho da tela (o mesmo card aparece numa sidebar estreita e num conteúdo largo). Qual ferramenta resolve?', o: ['Media query', 'Container query', 'Flexbox sozinho resolve', '@supports'], c: 1, e: 'Media query olha o viewport, não o espaço real do componente. Container query (container-type + @container) estiliza baseado no espaço disponível do elemento pai, tornando o componente reutilizável em qualquer contexto de layout.' },
  { t: 'CSS', s: 'css', q: 'Animar <code>transform: translateX()</code> é mais suave que animar <code>left</code>. Por quê?', o: ['transform usa menos memória', 'left dispara recálculo de layout a cada frame; transform só afeta a fase de composite, muitas vezes na GPU', 'left não é suportado em navegadores modernos', 'Não há diferença real de performance'], c: 1, e: 'left muda a posição no fluxo do documento (dispara layout + paint a cada frame). transform não afeta layout — o navegador só move a camada já pintada na composição, tipicamente acelerada por GPU.' },

  // B13 — Navegador & performance
  { t: 'Performance', s: 'performance-fe', q: 'Por que um <code>&lt;script&gt;</code> no &lt;head&gt; sem defer nem async atrasa a primeira pintura da página?', o: ['Scripts sempre bloqueiam CSS', 'O parser do HTML para de construir o DOM, baixa e executa o script antes de continuar', 'O navegador prioriza JavaScript sobre HTML por padrão', 'Isso só acontece em conexões lentas'], c: 1, e: 'O parser pode encontrar document.write no script, então ele para e executa antes de seguir. defer baixa em paralelo e roda só depois do HTML parseado; async roda assim que pronto, fora de ordem.' },
  { t: 'Performance', s: 'performance-fe', q: 'Uma rota carrega um editor de texto rico de 300kb usado por 5% dos usuários. Qual técnica evita que os outros 95% paguem esse custo?', o: ['Minificação agressiva', 'Code splitting: import() dinâmico carregando o editor só quando ele aparece na tela', 'Server-side rendering', 'Aumentar o cache do CDN'], c: 1, e: 'Split por componente com import() dinâmico (ou React.lazy) adia o download até o componente realmente ser necessário — os 95% que nunca abrem o editor nunca baixam esse bundle.' },
  { t: 'Performance', s: 'performance-fe', q: 'O texto pisca de uma fonte genérica pra uma fonte customizada (FOUT) e causa um "pulo" de layout perceptível. O que reduz o pulo, além de pré-carregar a fonte?', o: ['font-display: swap sozinho já resolve o pulo', 'Escolher uma fonte de fallback com métricas parecidas (ou usar size-adjust) pra minimizar a diferença de largura', 'Remover a fonte customizada', 'Usar apenas fontes do sistema operacional'], c: 1, e: 'font-display: swap evita texto invisível (FOIT) mas não evita o pulo em si — troca um problema pelo outro. Aproximar as métricas da fonte de fallback da fonte final é o que reduz o deslocamento de layout quando a troca acontece.' },

  // B14 — Front-end system design
  { t: 'FE System Design', s: 'fe-sysdesign', q: 'Num autocomplete, a resposta da busca por "a" chega depois da resposta por "abc" (a requisição mais lenta demorou mais). Sem tratamento, o que aparece na tela?', o: ['A lista de "abc" fica congelada', 'A lista de "a" sobrescreve a de "abc" por ter chegado por último', 'O navegador bloqueia a segunda requisição automaticamente', 'Nenhuma sugestão aparece'], c: 1, e: 'É uma condição de corrida de rede clássica. Corrige-se com AbortController cancelando a requisição anterior a cada nova tecla, ou um número de sequência que ignora resposta desatualizada.' },
  { t: 'FE System Design', s: 'fe-sysdesign', q: 'Por que um feed que recebe posts novos em tempo real deveria usar paginação por cursor em vez de offset?', o: ['Cursor é mais fácil de implementar', 'Offset quebra quando um item é inserido antes da posição atual enquanto o usuário rola, duplicando ou pulando itens', 'Offset não existe em bancos NoSQL', 'Cursor não precisa de índice no banco'], c: 1, e: 'Offset pede "a página N" por posição numérica; inserção concorrente desloca todo mundo. Cursor pede "os itens depois deste id/timestamp real", que permanece estável mesmo com inserção simultânea.' },
  { t: 'FE System Design', s: 'fe-sysdesign', q: 'Uma atualização otimista de "curtir" é aplicada na UI antes da resposta do servidor. O servidor rejeita. Qual é a forma correta de desfazer?', o: ['Recarregar a página inteira', 'Reverter para o estado anterior salvo (snapshot) e mostrar uma mensagem explicando o que houve', 'Ignorar o erro, já que o usuário não vai perceber', 'Tentar de novo automaticamente até funcionar'], c: 1, e: 'É necessário guardar o estado anterior antes de aplicar a mudança otimista, reverter para ele no erro (rollback), e comunicar — nunca reverter em silêncio, porque o usuário viu a mudança acontecer.' },

  // B15 — React avançado
  { t: 'React', s: 'react-avancado', q: 'Com o React Compiler ativo, você ainda pode precisar escrever useMemo manualmente. Quando?', o: ['Nunca mais é necessário sob nenhuma circunstância', 'Quando o código quebra as Regras do React (mutação fora de render, efeito colateral no corpo do componente) e o compiler não pode memoizar com segurança', 'Sempre que o componente tem mais de 3 props', 'Apenas em Server Components'], c: 1, e: 'O compiler memoiza automaticamente código que segue as Regras do React. Código que as quebra pode não ser otimizável com segurança — o compiler prefere não memoizar a memoizar errado, e useMemo manual ainda cobre esses casos e cálculos fora de componentes.' },
  { t: 'React', s: 'react-avancado', q: 'Uma lib como TanStack Query resolve o quê que um useEffect + fetch manual não resolve sozinho, pra dado que vem de uma API?', o: ['Apenas estiliza o estado de loading', 'Noção de staleness com refetch automático (foco, reconexão) e deduplicação de requisições simultâneas pelo mesmo dado', 'Substitui a necessidade de um backend', 'Faz cache permanente que nunca expira'], c: 1, e: 'A lib trata o dado como "estado de servidor": sabe quando ficou desatualizado e refaz a busca automaticamente em certos eventos, além de deduplicar pedidos concorrentes pelo mesmo recurso — tudo isso replicável à mão, mas com bem mais código.' },
  { t: 'React', s: 'react-avancado', q: 'Um componente tem 15 props booleanas controlando o que é renderizado. Qual é o padrão que resolve isso trocando configuração por composição?', o: ['Prop drilling', 'Compound components (ex.: <Card><Card.Icon/><Card.Footer/></Card>)', 'HOC (higher-order component)', 'Context API sozinho'], c: 1, e: 'Compound components deixa quem usa decidir o que existe simplesmente incluindo ou não a subpeça, sem prop booleana nenhuma — evita a combinatória de condicionais dentro de um único componente configurável.' },

  // B16 — Design de APIs
  { t: 'APIs', s: 'apis', q: 'Um app mobile precisa de dado de 4 endpoints REST diferentes pra montar uma tela, cada requisição com 200ms de latência de rede. Qual padrão reduz isso a uma chamada do cliente?', o: ['GraphQL é a única solução possível', 'BFF: uma camada fina específica pro cliente que agrega as 4 chamadas no servidor e devolve um payload único', 'Aumentar o timeout do cliente', 'Usar WebSocket em vez de REST'], c: 1, e: 'Um Backend for Frontend concentra as chamadas onde a latência entre elas é baixa (dentro da infraestrutura do servidor) e devolve tudo agregado — o cliente paga a latência de rede uma vez, não quatro.' },
  { t: 'APIs', s: 'apis', q: 'Por que resolvers do GraphQL sofrem com o problema N+1, e qual a correção padrão?', o: ['GraphQL não tem esse problema, só REST', 'Cada campo de relação numa lista dispara uma query por item por padrão; DataLoader agrupa (batch) essas chamadas feitas no mesmo tick numa consulta só', 'A correção é sempre usar REST em vez de GraphQL', 'O problema só existe em bancos NoSQL'], c: 1, e: 'Uma lista de N posts com autor dispara 1 query pros posts + N queries pros autores por padrão. DataLoader junta as N chamadas de autor feitas no mesmo tick numa única consulta em lote (WHERE id IN (...)).' },
  { t: 'APIs', s: 'apis', q: 'Um provedor de pagamento reenvia o mesmo webhook duas vezes (entrega at-least-once). O que garante que seu handler não duplica o efeito?', o: ['Confiar que o provedor não reenvia sem motivo', 'Gravar o id do evento com constraint UNIQUE na mesma transação do efeito, fazendo a segunda execução virar no-op', 'Aumentar o timeout de resposta do webhook', 'Ignorar eventos repetidos pelo timestamp'], c: 1, e: 'Idempotência do lado de quem recebe é a defesa real: uma constraint UNIQUE na mesma transação garante que a segunda tentativa esbarra e não duplica o efeito, independente de quantas vezes o evento chegue.' },

  // B17 — Produção
  { t: 'Produção', s: 'producao', q: 'Por que "alertar quando a CPU passa de 80%" costuma gerar mais ruído do que "alertar quando a latência p99 passa de 2s"?', o: ['CPU é mais difícil de medir', 'CPU alta é uma causa possível, não necessariamente um sintoma que o usuário sente; latência é o que o usuário experimenta de fato', 'Latência não pode ser medida com precisão', 'Não há diferença real entre os dois'], c: 1, e: 'A prática recomendada é alertar no sintoma percebido pelo usuário (latência, taxa de erro) e usar métricas de causa (CPU, memória) só para investigar depois que o alerta de sintoma já disparou.' },
  { t: 'Produção', s: 'producao', q: 'Sua SLO mensal de disponibilidade já consumiu metade do error budget, faltando duas semanas do mês. O que a prática de SRE recomenda?', o: ['Ignorar, já que ainda resta metade do budget', 'Desacelerar lançamentos arriscados e priorizar confiabilidade até o budget renovar', 'Aumentar a SLO imediatamente pra evitar o problema', 'Parar todo deploy até o fim do mês'], c: 1, e: 'O error budget existe pra negociar entre velocidade de lançamento e confiabilidade. Consumido em excesso, a prática comum é reduzir risco (menos lançamentos arriscados) pelo resto do período, sem necessariamente parar tudo.' },
  { t: 'Produção', s: 'producao', q: 'O que muda, na prática, num postmortem "sem culpa" (blameless) em relação a um postmortem comum?', o: ['Não se investiga a causa raiz', 'O foco vai para o sistema que permitiu o erro acontecer, não para punir quem cometeu o erro — o que gera relatos mais completos e honestos', 'Ninguém é informado do incidente', 'É apenas um nome mais educado pro mesmo processo'], c: 1, e: 'Assumir que a pessoa tomou a melhor decisão possível com a informação disponível desloca o foco pro sistema (falta de alerta, processo, documentação) — e isso remove o incentivo de esconder o próprio erro, gerando relatos mais completos.' },

  // B18 — Senioridade
  { t: 'Senioridade', s: 'senioridade', q: 'Qual é a diferença central entre o esperado de um engenheiro pleno e de um sênior, além de conhecimento técnico?', o: ['Sênior escreve código mais rápido', 'Escopo de decisão e capacidade de operar bem com ambiguidade, comunicando trade-offs por escrito', 'Sênior não precisa mais revisar código de outros', 'A diferença é só o tempo de empresa'], c: 1, e: 'Pleno executa bem um problema já definido; sênior é chamado justamente quando o problema não está bem definido, precisando decidir o que construir e comunicar o porquê — não apenas saber mais sintaxe ou API.' },
  { t: 'Senioridade', s: 'senioridade', q: 'Num code review, qual a diferença prática entre marcar um comentário como bloqueante e como sugestão?', o: ['Não há diferença, todo comentário deve ser tratado igual', 'Bloqueante exige mudança antes do merge (bug, falha de segurança); sugestão é uma opinião válida sem travar o merge', 'Sugestão é sempre ignorada pelo autor', 'Bloqueante só pode vir do tech lead'], c: 1, e: 'Sem essa distinção explícita, todo comentário vira implicitamente bloqueante e o review fica lento e desgastante — distinguir os dois deixa claro o que realmente precisa mudar versus o que é só uma consideração.' },
  { t: 'Senioridade', s: 'senioridade', q: 'Você discordou tecnicamente de uma decisão do tech lead, argumentou, e ele decidiu seguir do jeito dele. O que "discordar e se comprometer" significa na prática?', o: ['Continuar insistindo na reunião seguinte', 'Registrar a discordância uma vez, e então executar a decisão com o mesmo empenho de quem concorda, sem sabotar passivamente', 'Sabotar silenciosamente a implementação', 'Escalar imediatamente para um nível acima'], c: 1, e: 'É registrar objeção de forma clara, garantir que a decisão considerou os fatos, e então executar com empenho real — reservado para decisões em que você genuinamente discorda, não para todo desacordo de preferência.' },

  // B19 — Processo seletivo
  { t: 'Processo seletivo', s: 'processo', q: 'Um recrutador pergunta sua pretensão salarial antes de revelar a faixa da vaga. Qual é a resposta mais defensável?', o: ['Dar um número alto de propósito', 'Devolver a pergunta pedindo a faixa orçada da posição antes de dar um número', 'Recusar responder e encerrar a conversa', 'Dar o número mais baixo que aceitaria'], c: 1, e: 'Quem fala um número primeiro perde alavancagem de negociação — se for baixo, ancora abaixo do que a empresa pagaria; se for alto sem saber a faixa, pode ser descartado sem conversa. Pedir a faixa primeiro é a prática recomendada.' },
  { t: 'Processo seletivo', s: 'processo', q: 'Por que "responsável por desenvolvimento de features" é uma linha mais fraca de currículo que "reduzi o tempo de build de 8min pra 2min removendo dependência circular"?', o: ['A primeira é mais curta e objetiva', 'A primeira descreve responsabilidade genérica; a segunda tem causa, ação e resultado quantificado', 'Não há diferença real de qualidade', 'A segunda menciona tecnologia específica, o que é sempre pior'], c: 1, e: 'A frase genérica poderia ter sido escrita por qualquer pessoa no cargo. A segunda prova impacto mensurável e específico, que é o que recrutador técnico procura ao filtrar currículos.' },
  { t: 'Processo seletivo', s: 'processo', q: 'Comparado a um processo típico no Brasil, qual o peso da entrevista comportamental num loop de big tech no exterior?', o: ['É sempre menos importante que a técnica', 'Costuma ser uma rodada inteira separada, com peso equivalente a uma rodada técnica e influência direta no nível oferecido', 'Não existe entrevista comportamental fora do Brasil', 'É substituída por um teste de personalidade automatizado'], c: 1, e: 'No exterior, comportamental frequentemente é rodada própria que ajuda a decidir nível (sênior vs. staff, por exemplo) — não é um "extra" superficial como costuma ser tratado em processos mais curtos no Brasil.' },
];
